"""add_uuid_limit

Revision ID: 6222361e45c0
Revises: 48a6bcb8bba1
Create Date: 2026-09-29 20:21:59.806633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6222361e45c0'
down_revision = '48a6bcb8bba1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid_limit', sa.BigInteger(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid_limit', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('uuid_limit')

    with op.batch_alter_table('user_templates', schema=None) as batch_op:
        batch_op.drop_column('uuid_limit')

    # ### end Alembic commands ###
